#!/bin/bash
# Railway Fix Script

echo "🔧 Fixing Railway Configuration..."
echo ""
echo "Please run these commands in your Railway dashboard or CLI:"
echo ""
echo "1. Install Railway CLI (if not installed):"
echo "   npm i -g @railway/cli"
echo ""
echo "2. Login to Railway:"
echo "   railway login"
echo ""
echo "3. Link to your project:"
echo "   railway link"
echo ""
echo "4. Clear custom start command:"
echo "   railway variables set START_COMMAND=''"
echo ""
echo "5. Force redeploy:"
echo "   railway up --detach"
echo ""
echo "Or manually in Railway Dashboard:"
echo "  → Settings → Deploy → Clear 'Custom Start Command'"
echo "  → Settings → Build → Verify 'Dockerfile' is selected"
echo "  → Trigger a new deployment"
